package ru.fccland.portal.rt;

import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.0.9
 * 2017-08-04T11:42:52.004+07:00
 * Generated source version: 3.0.9
 * 
 */
@WebServiceClient(name = "RosreestrService", 
                  wsdlLocation = "file:/home/void/work/igrr/igrr.git/ru.thprom.igrr.smev2/src/main/wsdl/rr.wsdl",
                  targetNamespace = "http://portal.fccland.ru/rt/") 
public class RosreestrService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://portal.fccland.ru/rt/", "RosreestrService");
    public final static QName RosreestrServicePort = new QName("http://portal.fccland.ru/rt/", "RosreestrServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/void/work/igrr/igrr.git/ru.thprom.igrr.smev2/src/main/wsdl/rr.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RosreestrService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/void/work/igrr/igrr.git/ru.thprom.igrr.smev2/src/main/wsdl/rr.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RosreestrService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RosreestrService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RosreestrService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RosreestrService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RosreestrService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RosreestrService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns RosreestrServicePortType
     */
    @WebEndpoint(name = "RosreestrServicePort")
    public RosreestrServicePortType getRosreestrServicePort() {
        return super.getPort(RosreestrServicePort, RosreestrServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RosreestrServicePortType
     */
    @WebEndpoint(name = "RosreestrServicePort")
    public RosreestrServicePortType getRosreestrServicePort(WebServiceFeature... features) {
        return super.getPort(RosreestrServicePort, RosreestrServicePortType.class, features);
    }

}
