package ru.fccland.portal.rt;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.9
 * 2017-08-04T11:42:51.963+07:00
 * Generated source version: 3.0.9
 * 
 */
@WebService(targetNamespace = "http://portal.fccland.ru/rt/", name = "RosreestrServicePortType")
@XmlSeeAlso({ru.gosuslugi.smev.rev111111.ObjectFactory.class, org.w3._2004._08.xop.include.ObjectFactory.class, ru.fccland.portal.types.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RosreestrServicePortType {

    @WebMethod(operationName = "CreateRequest", action = "http://portal.rosreestr.ru/CreateRequest")
    @WebResult(name = "createRequestResponse", targetNamespace = "http://portal.fccland.ru/rt/", partName = "data")
    public ru.gosuslugi.smev.rev111111.CreateRequestResponseMessage createRequest(
	    @WebParam(partName = "data", name = "createRequestRequest", targetNamespace = "http://portal.fccland.ru/rt/")
		    ru.gosuslugi.smev.rev111111.CreateRequestRequestMessage data
    );

    @WebMethod(operationName = "GetEvents", action = "http://portal.rosreestr.ru/GetEvents")
    @WebResult(name = "getEventsResponse", targetNamespace = "http://portal.fccland.ru/rt/", partName = "data")
    public ru.gosuslugi.smev.rev111111.GetEventsResponseMessage getEvents(
	    @WebParam(partName = "data", name = "getEventsRequest", targetNamespace = "http://portal.fccland.ru/rt/")
		    ru.gosuslugi.smev.rev111111.GetEventsRequestMessage data
    );

    @WebMethod(operationName = "LoadEventDetails", action = "http://portal.rosreestr.ru/LoadEventDetails")
    @WebResult(name = "loadEventDetailsResponse", targetNamespace = "http://portal.fccland.ru/rt/", partName = "data")
    public ru.gosuslugi.smev.rev111111.LoadEventDetailsResponseMessage loadEventDetails(
	    @WebParam(partName = "data", name = "loadEventDetailsRequest", targetNamespace = "http://portal.fccland.ru/rt/")
		    ru.gosuslugi.smev.rev111111.LoadEventDetailsRequestMessage data
    );

    @WebMethod(operationName = "GetStatus", action = "http://portal.rosreestr.ru/GetStatus")
    @WebResult(name = "getStatusResponse", targetNamespace = "http://portal.fccland.ru/rt/", partName = "data")
    public ru.gosuslugi.smev.rev111111.GetStatusResponseMessage getStatus(
	    @WebParam(partName = "data", name = "getStatusRequest", targetNamespace = "http://portal.fccland.ru/rt/")
		    ru.gosuslugi.smev.rev111111.GetStatusRequestMessage data
    );
}
